version: '2.2'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - 8086:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./drinks_db.sql:/docker-entrypoint-initdb.d/drinks_db.sql  # Mount SQL file for initialization

volumes:
  db_data:
