apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8081
      nodePort: 30001  # Expose port 80 on the node via port 30001
  type: NodePort