apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: m321-25-ap21a
      containers:
        - name: backend
          image: backend:latest
          ports:
            - containerPort: 8081
          env:
            - name: POSTGRES_URL
              value: "postgres-service"
            - name: POSTGRES_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8081
  type: NodePort