apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 80
      nodePort: 30001  # Expose port 80 on the node via port 30001
  type: NodePort