apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 5432
      nodePort: 30001  # Expose port 80 on the node via port 30001
