apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 5432
      nodePort: 30003  # Expose port 80 on the node via port 30003
  type: NodePort